### ISSUE TITLE
"No features/bugs/chores available!"

### ISSUE THREAD

**Issue by logankoester** [trydionel/git-pivotal#6]
I may just be missing something as I'm fairly new to Tracker, but after setting up the git config correctly and calling "git feature", I receive the output "No features available!" even though there are lots of features in my Icebox as well as in my Current iteration.

Some of my features/bugs/chores are owned by a user, some are not, some are started, some are not yet. What do I have to do to make a feature/bug/chore "available"?

Perhaps this is a bug? I'm using Ruby 1.9.1p378 with RVM.

**Comment by trydionel** [comment]
Hi Logan,

Thanks for the note.  I've verified the code against 1.9.1p378, so I think it's a configuration issue rather than a code issue.

git-pivotal will only touch stories that are in your current and backlog queues -- not the icebox.  Beyond that, git-pivotal will only pull stories of the appropriate type (e.g., `git feature` will only pull feature stories) that are in the unstarted state.  Nothing extra required.

If you're still not able to get any results, make sure Pivotal Tracker is up (I've seen some poor performance in the last week) and that your API key is correctly entered.  Post back if you still don't have any luck.

Jeff

**Comment by logankoester** [comment]
Thanks for the explanation. Problem solved :)
